### ISSUE TITLE
[BUG]添加环境变量返回500

### ISSUE THREAD

**Issue by asdyyx1** [Ukenn2112/qinglongAPI_doc#1]
应用设置权限 环境变量
使用 Token 返回环境变量详情
可以返回所有的环境变量

使用 Token 添加环境变量
返回500
```
{"code":500,"message":"celebrate request validation failed"}
```

**Comment by Ukenn2112** [comment]
查看qinglong那边的issue发现最近有过类似情况
https://github.com/whyour/qinglong/issues/1130
https://github.com/whyour/qinglong/issues/1078

我是照着源码写的文档，我使用postman测试也出现了同样的情况。。应该是qinglong那边的问题吧。
https://github.com/whyour/qinglong/blob/d23049b2fe7aeedeb447d6cb896fdf5afd207a8f/back/api/env.ts#L23

**Comment by Ukenn2112** [comment]
解决办法：
https://github.com/whyour/qinglong/issues/1151#issuecomment-1047759185
感谢这位朋友的补充

envs添加实际是支持批量的，所以是个list，改成数组就行了，文档已更新https://github.com/Ukenn2112/qinglongAPI_doc/commit/968398274c9351b26afdfafb5c3cfa07bb6ca4f8
