### ISSUE TITLE
是否可以注明对应的qinglong版本？

### ISSUE THREAD

**Issue by ainexur** [Ukenn2112/qinglongAPI_doc#2]
qinglong版本不一致，接口返回的请求结果也不一样。

我在测试环境和实际环境（qinglong版本不一样）跑api的结果不同

参考/open/envs/{id}：
2.10.12可以正常根据id查询指定envs，2.11.3则返回的envs并非指定id的envs

**Comment by Ukenn2112** [comment]
2.11.3之前老的id是叫`_id`来着现在改成了 `id` 
理论上应该一样的吧

不过说的也是我注明一下适用版本

**Comment by ainexur** [comment]
2.11.3复现：/envs/10，/envs/11/均为同一个返回结果。是否/envs/{id}接口不适配这个版本

**Comment by Ukenn2112** [comment]
https://github.com/whyour/qinglong/blob/a099d09af7668a46ae4d379e1d40aa5c3463c516/back/api/env.ts#L169

我刚刚试了一下确实是无论id是多少都是同一个变量。。上面是相关源码你可以研究研究看看，不清楚是qinglong的问题还是使用方法不对，有待确定
