### ISSUE TITLE
更新环境变量提交失败

### ISSUE THREAD

**Issue by LevenYi** [Ukenn2112/qinglongAPI_doc#3]
获取环境变量和添加环境变量没问题，但是更新环境变量会出错，请问一下是不是这个id的问题，
![image](https://user-images.githubusercontent.com/50928588/172065422-7b6e5537-2118-4281-8aa7-7196bfcc3493.png)
获取环境变量的时候返回环境变量其中一项参数是_id，但我改成_id同样还是报错
![image](https://user-images.githubusercontent.com/50928588/172065498-835bf324-9638-4576-93bd-343768cb239a.png)

**Comment by Ukenn2112** [comment]
env的id不长这样吧

**Comment by LevenYi** [comment]
> env的id不长这样吧

2fa3fc5a-9e35-4b47-b3d2-064ada6cbef3
可能是青龙版本原因，我获取的环境变量信息是这样的

**Comment by LevenYi** [comment]
> env的id不长这样吧

![2022-06-06 19-54-20 的屏幕截图](https://user-images.githubusercontent.com/50928588/172155866-f9bcb92d-8f31-4a1e-bf1f-58a75e974785.png)
可能是青龙版本原因，我获取的环境变量信息是这样的

**Comment by LevenYi** [comment]
> env的id不长这样吧

可能是青龙版本（2.10.12)原因，我获取的环境变量信息是这样的
![2022-06-06 19-54-20 的屏幕截图](https://user-images.githubusercontent.com/50928588/172156106-dd0a1d9e-d42e-4b35-b356-c6e1a8732b71.png)

**Comment by Ukenn2112** [comment]
> > env的id不长这样吧
> 
> 可能是青龙版本（2.10.12)原因，我获取的环境变量信息是这样的 ![2022-06-06 19-54-20 的屏幕截图](https://user-images.githubusercontent.com/50928588/172156106-dd0a1d9e-d42e-4b35-b356-c6e1a8732b71.png)

哦哦 `2.10.12` 的话用这个试试 `2.11` 之前 `id` 都叫 `_id` 来着
```
{
  "value": "变量值",
  "name": "变量名",
  "remarks": "备注",
  "_id": 0
}
```

**Comment by LevenYi** [comment]
> 

解决了，谢谢。是自己智障了，忘记把post改成put了，挂不得_id也不对
