### ISSUE TITLE
禁用环境变量的问题

### ISSUE THREAD

**Issue by yiyule10** [Ukenn2112/qinglongAPI_doc#5]
可以列出一个示例吗？
这个示例有点看不懂`[
  0
]`

**Comment by Ukenn2112** [comment]
可以同时传多个环境变量配置的ID 以list [2333, 22444, 2333]

**Comment by yiyule10** [comment]
> 可以同时传多个环境变量配置的ID 以list [2333, 22444, 2333]

好的，非常感谢，已经实现了，谢谢
